[package]
name = "risingwave_meta"
version = "0.1.11"
edition = "2021"

[dependencies]
anyhow = "1"
assert_matches = "1"
async-stream = "0.3"
async-trait = "0.1"
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "3", features = ["derive", "env"] }
crc32fast = "1"
derivative = "2"
either = "1"
etcd-client = "0.10"
fail = "0.5"
function_name = "0.3.0"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hex = "0.4"
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
memcomparable = { path = "../utils/memcomparable" }
num-integer = "0.1"
num-traits = "0.2"
parking_lot = { version = "0.12", features = ["arc_lock"] }
paste = "1"
prometheus = "0.13"
prost = "0.11"
rand = "0.8"
risingwave_common = { path = "../common" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_connector = { path = "../connector" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
scopeguard = "1"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
smallvec = "1"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.2.1", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[target.'cfg(not(madsim))'.dependencies]
axum = "0.5"
tower-http = { version = "0.3", features = ["add-extension", "cors", "fs"] }

[dev-dependencies]
assert_matches = "1"
rand = "0.8"
risingwave_test_runner = { path = "../test_runner" }
static_assertions = "1"
tempfile = "3"

[features]
test = []
failpoints = ["fail/failpoints"]
