[package]
name = "risingwave_test_runner"
version = "0.1.11"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fail = "0.5"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
