[package]
name = "risingwave_rt"
version = "0.1.11"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
console = "0.15"
console-subscriber = "0.1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
pprof = { version = "0.10", features = ["flamegraph"] }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs"
] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "parking_lot"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
