[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "--cfg", "tokio_unstable"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "--cfg", "tokio_unstable"
]

[build]
rustflags = ["--cfg", "tokio_unstable"]
