[package]
name = "risingwave_hummock_sdk"
version = "0.1.10"
edition = "2021"

[dependencies]
bytes = "1"
hex = "0.4"
itertools = "0.10"
log = "0.4"
madsim = "=0.2.0-alpha.5"
prost = "0.10"
risingwave_common = { path = "../../common" }
risingwave_pb = { path = "../../prost" }
tokio = { version = "=0.2.0-alpha.5", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
