[package]
name = "risingwave_hummock_sdk"
version = "0.1.11"
edition = "2021"

[dependencies]
bytes = "1"
hex = "0.4"
itertools = "0.10"
num-derive = "0.3"
num-traits = "0.2"
parking_lot = "0.12"
prost = "0.11"
risingwave_common = { path = "../../common" }
risingwave_pb = { path = "../../prost" }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
